runtime: python37
entrypoint: gunicorn app:app -w 4 -k uvicorn.workers.UvicornWorker
env_variables:
  DB_HOST: "localhost:5432"
  DB_NAME: "wowsurveysdb"
  DB_USER: "wowsurveys"
  DB_PASSWORD: "bkIheZEndZwI8nPZz7Addrc4GAH9qbwmFa2vDlV9"
  DB_SOCKET_DIR: "/cloudsql"
  DB_CONNECTION_NAME: "wowsurveys:europe-west1:wowsurveysdb"
